import type { Topic } from "./schema";

export const TOPICS: Topic[] = [
  // Level 1: Explorer (1-2 years) - Concrete, everyday objects
  {
    id: "animal-friends",
    name: "Animal Friends",
    description:
      "Meet friendly farm animals and pets! Perfect for little ones learning their first animal names.",
    learningGoals: [
      "Recognize common farm animals",
      "Associate animal names with their appearance",
      "Build early vocabulary",
    ],
    icon: "🐶",
    level: 1,
    items: [
      { word: "dog", emoji: "🐕" },
      { word: "cat", emoji: "🐈" },
      { word: "pig", emoji: "🐷" },
      { word: "cow", emoji: "🐄" },
      { word: "chicken", emoji: "🐔" },
      { word: "duck", emoji: "🦆" },
      { word: "horse", emoji: "🐎" },
      { word: "sheep", emoji: "🐑" },
      { word: "rabbit", emoji: "🐇" },
      { word: "fish", emoji: "🐟" },
      { word: "bird", emoji: "🐦" },
      { word: "mouse", emoji: "🐭" },
      { word: "frog", emoji: "🐸" },
      { word: "turtle", emoji: "🐢" },
      { word: "goat", emoji: "🐐" },
      { word: "hamster", emoji: "🐹" },
      { word: "chick", emoji: "🐤" },
      { word: "rooster", emoji: "🐓" },
      { word: "turkey", emoji: "🦃" },
      { word: "snail", emoji: "🐌" },
      { word: "bee", emoji: "🐝" },
      { word: "ladybug", emoji: "🐞" },
      { word: "ant", emoji: "🐜" },
      { word: "parrot", emoji: "🦜" },
      { word: "peacock", emoji: "🦚" },
    ],
  },
  {
    id: "fruits",
    name: "Fruits",
    description:
      "Discover colorful fruits from the kitchen! Learn to identify delicious fruits by their shapes and colors.",
    learningGoals: [
      "Identify common fruits",
      "Learn fruit names",
      "Connect fruits to everyday eating",
    ],
    icon: "🍎",
    level: 1,
    items: [
      { word: "apple", emoji: "🍎" },
      { word: "banana", emoji: "🍌" },
      { word: "strawberry", emoji: "🍓" },
      { word: "orange", emoji: "🍊" },
      { word: "grapes", emoji: "🍇" },
      { word: "watermelon", emoji: "🍉" },
      { word: "lemon", emoji: "🍋" },
      { word: "pear", emoji: "🍐" },
      { word: "peach", emoji: "🍑" },
      { word: "cherries", emoji: "🍒" },
      { word: "pineapple", emoji: "🍍" },
      { word: "coconut", emoji: "🥥" },
      { word: "kiwi", emoji: "🥝" },
      { word: "mango", emoji: "🥭" },
      { word: "blueberries", emoji: "🫐" },
      { word: "melon", emoji: "🍈" },
      { word: "green apple", emoji: "🍏" },
    ],
  },
  {
    id: "vehicles",
    name: "Vehicles",
    description:
      "Things that go! Explore cars, trucks, and more vehicles your child sees every day.",
    learningGoals: [
      "Name common vehicles",
      "Understand that vehicles help us travel",
      "Recognize vehicles in daily life",
    ],
    icon: "🚗",
    level: 1,
    items: [
      { word: "car", emoji: "🚗" },
      { word: "bus", emoji: "🚌" },
      { word: "train", emoji: "🚂" },
      { word: "truck", emoji: "🚚" },
      { word: "airplane", emoji: "✈️" },
      { word: "boat", emoji: "🚢" },
      { word: "bicycle", emoji: "🚲" },
      { word: "helicopter", emoji: "🚁" },
      { word: "motorcycle", emoji: "🏍️" },
      { word: "tractor", emoji: "🚜" },
      { word: "ambulance", emoji: "🚑" },
      { word: "fire truck", emoji: "🚒" },
      { word: "police car", emoji: "🚓" },
      { word: "taxi", emoji: "🚕" },
      { word: "rocket", emoji: "🚀" },
      { word: "sailboat", emoji: "⛵" },
      { word: "canoe", emoji: "🛶" },
      { word: "scooter", emoji: "🛵" },
      { word: "metro", emoji: "🚇" },
      { word: "trolley", emoji: "🚎" },
      { word: "race car", emoji: "🏎️" },
      { word: "pickup truck", emoji: "🛻" },
      { word: "minibus", emoji: "🚐" },
    ],
  },
  {
    id: "clothing",
    name: "Clothing",
    description:
      "What do we wear? Learn about everyday clothing items from head to toe.",
    learningGoals: [
      "Identify clothing items",
      "Connect clothes to body parts",
      "Build dressing vocabulary",
    ],
    icon: "👕",
    level: 1,
    items: [
      { word: "shoe", emoji: "👟" },
      { word: "shirt", emoji: "👕" },
      { word: "hat", emoji: "🎩" },
      { word: "pants", emoji: "👖" },
      { word: "dress", emoji: "👗" },
      { word: "socks", emoji: "🧦" },
      { word: "coat", emoji: "🧥" },
      { word: "gloves", emoji: "🧤" },
      { word: "scarf", emoji: "🧣" },
      { word: "boots", emoji: "🥾" },
      { word: "glasses", emoji: "👓" },
      { word: "tie", emoji: "👔" },
      { word: "crown", emoji: "👑" },
      { word: "purse", emoji: "👛" },
      { word: "backpack", emoji: "🎒" },
      { word: "sunglasses", emoji: "🕶️" },
      { word: "sandal", emoji: "🩴" },
      { word: "shorts", emoji: "🩳" },
      { word: "cap", emoji: "🧢" },
      { word: "high heel", emoji: "👠" },
      { word: "handbag", emoji: "👜" },
      { word: "watch", emoji: "⌚" },
      { word: "ring", emoji: "💍" },
    ],
  },
  {
    id: "colors",
    name: "Colors",
    description:
      "A rainbow of colors! Practice naming basic colors that are everywhere around us.",
    learningGoals: [
      "Recognize primary colors",
      "Name colors accurately",
      "Notice colors in the environment",
    ],
    icon: "🌈",
    level: 1,
    items: [
      { color: "red" },
      { color: "blue" },
      { color: "green" },
      { color: "yellow" },
      { color: "orange" },
      { color: "purple" },
      { color: "pink" },
      { color: "brown" },
      { color: "black" },
      { color: "white" },
      { color: "gray" },
      { color: "gold" },
      { color: "silver" },
      { color: "cyan" },
      { color: "magenta" },
      { color: "navy" },
      { color: "teal" },
      { color: "lime" },
      { color: "coral" },
      { color: "salmon" },
      { color: "khaki" },
      { color: "tan" },
      { color: "maroon" },
      { color: "olive" },
      { color: "indigo" },
    ],
  },

  // Level 2: Discoverer (3-5 years) - Categorization, emotions, attributes
  {
    id: "wild-animals",
    name: "Wild Animals",
    description:
      "Safari time! Discover amazing animals from jungles, oceans, and beyond.",
    learningGoals: [
      "Learn about animals from different habitats",
      "Understand animal diversity",
      "Expand animal vocabulary",
    ],
    icon: "🦁",
    level: 2,
    items: [
      { word: "lion", emoji: "🦁" },
      { word: "elephant", emoji: "🐘" },
      { word: "giraffe", emoji: "🦒" },
      { word: "zebra", emoji: "🦓" },
      { word: "monkey", emoji: "🐵" },
      { word: "bear", emoji: "🐻" },
      { word: "shark", emoji: "🦈" },
      { word: "dolphin", emoji: "🐬" },
      { word: "butterfly", emoji: "🦋" },
      { word: "octopus", emoji: "🐙" },
      { word: "penguin", emoji: "🐧" },
      { word: "kangaroo", emoji: "🦘" },
      { word: "whale", emoji: "🐋" },
      { word: "tiger", emoji: "🐅" },
      { word: "crocodile", emoji: "🐊" },
      { word: "snake", emoji: "🐍" },
      { word: "owl", emoji: "🦉" },
      { word: "fox", emoji: "🦊" },
      { word: "panda", emoji: "🐼" },
      { word: "koala", emoji: "🐨" },
      { word: "gorilla", emoji: "🦍" },
      { word: "hippo", emoji: "🦛" },
      { word: "rhino", emoji: "🦏" },
      { word: "camel", emoji: "🐪" },
      { word: "bat", emoji: "🦇" },
      { word: "eagle", emoji: "🦅" },
      { word: "flamingo", emoji: "🦩" },
      { word: "lobster", emoji: "🦞" },
      { word: "crab", emoji: "🦀" },
      { word: "jellyfish", emoji: "🪼" },
    ],
  },
  {
    id: "food",
    name: "Food",
    description:
      "Yummy foods from around the world! From pizza to noodles, discover tasty treats.",
    learningGoals: [
      "Identify various foods",
      "Learn food vocabulary",
      "Connect food to meals",
    ],
    icon: "🍕",
    level: 2,
    items: [
      { word: "pizza", emoji: "🍕" },
      { word: "ice cream", emoji: "🍦" },
      { word: "hamburger", emoji: "🍔" },
      { word: "donut", emoji: "🍩" },
      { word: "popcorn", emoji: "🍿" },
      { word: "cake", emoji: "🎂" },
      { word: "cookie", emoji: "🍪" },
      { word: "bread", emoji: "🍞" },
      { word: "cheese", emoji: "🧀" },
      { word: "egg", emoji: "🥚" },
      { word: "rice", emoji: "🍚" },
      { word: "noodles", emoji: "🍜" },
      { word: "hot dog", emoji: "🌭" },
      { word: "taco", emoji: "🌮" },
      { word: "sushi", emoji: "🍣" },
      { word: "bacon", emoji: "🥓" },
      { word: "salad", emoji: "🥗" },
      { word: "french fries", emoji: "🍟" },
      { word: "sandwich", emoji: "🥪" },
      { word: "pancakes", emoji: "🥞" },
      { word: "waffle", emoji: "🧇" },
      { word: "pretzel", emoji: "🥨" },
      { word: "croissant", emoji: "🥐" },
      { word: "burrito", emoji: "🌯" },
      { word: "steak", emoji: "🥩" },
      { word: "shrimp", emoji: "🍤" },
      { word: "dumpling", emoji: "🥟" },
      { word: "pie", emoji: "🥧" },
      { word: "chocolate", emoji: "🍫" },
      { word: "lollipop", emoji: "🍭" },
    ],
  },
  {
    id: "nature",
    name: "Nature",
    description:
      "Explore the natural world! From sunny skies to snowy mountains, discover nature's wonders.",
    learningGoals: [
      "Identify natural phenomena",
      "Learn about weather and landscapes",
      "Appreciate the natural world",
    ],
    icon: "🌻",
    level: 2,
    items: [
      { word: "sun", emoji: "☀️" },
      { word: "rain", emoji: "🌧️" },
      { word: "rainbow", emoji: "🌈" },
      { word: "cloud", emoji: "☁️" },
      { word: "snow", emoji: "❄️" },
      { word: "star", emoji: "⭐" },
      { word: "moon", emoji: "🌙" },
      { word: "rose", emoji: "🌹" },
      { word: "sunflower", emoji: "🌻" },
      { word: "tree", emoji: "🌳" },
      { word: "mushroom", emoji: "🍄" },
      { word: "mountain", emoji: "⛰️" },
      { word: "volcano", emoji: "🌋" },
      { word: "beach", emoji: "🏖️" },
      { word: "wave", emoji: "🌊" },
      { word: "fire", emoji: "🔥" },
      { word: "snowman", emoji: "⛄" },
      { word: "cactus", emoji: "🌵" },
      { word: "tulip", emoji: "🌷" },
      { word: "leaf", emoji: "🍃" },
      { word: "palm tree", emoji: "🌴" },
      { word: "lightning", emoji: "⚡" },
      { word: "tornado", emoji: "🌪️" },
      { word: "comet", emoji: "☄️" },
      { word: "full moon", emoji: "🌕" },
      { word: "hibiscus", emoji: "🌺" },
      { word: "desert island", emoji: "🏝️" },
      { word: "sunrise", emoji: "🌅" },
      { word: "clover", emoji: "🍀" },
      { word: "shell", emoji: "🐚" },
    ],
  },
  {
    id: "emotions",
    name: "Emotions",
    description:
      "How do you feel? Learn to recognize and name different emotions and feelings.",
    learningGoals: [
      "Identify facial expressions",
      "Name common emotions",
      "Build emotional vocabulary",
    ],
    icon: "😊",
    level: 2,
    items: [
      { word: "happy", emoji: "😊" },
      { word: "sad", emoji: "😢" },
      { word: "angry", emoji: "😠" },
      { word: "scared", emoji: "😨" },
      { word: "sleepy", emoji: "😴" },
      { word: "love", emoji: "🥰" },
      { word: "worried", emoji: "😟" },
      { word: "crying", emoji: "😭" },
      { word: "thinking", emoji: "🤔" },
      { word: "confused", emoji: "😕" },
      { word: "surprised", emoji: "😮" },
      { word: "silly", emoji: "🤪" },
      { word: "cool", emoji: "😎" },
      { word: "sick", emoji: "🤒" },
      { word: "laughing", emoji: "😂" },
      { word: "winking", emoji: "😉" },
      { word: "shy", emoji: "😳" },
      { word: "hungry", emoji: "🤤" },
      { word: "yawning", emoji: "🥱" },
      { word: "excited", emoji: "🤩" },
    ],
  },
  {
    id: "shapes",
    name: "Shapes",
    description:
      "Shapes are everywhere! Learn to spot circles, squares, and more geometric friends.",
    learningGoals: [
      "Recognize basic shapes",
      "Find shapes in everyday objects",
      "Build spatial awareness",
    ],
    icon: "⭐",
    level: 2,
    items: [
      { word: "circle", emoji: "⚫" },
      { word: "square", emoji: "🟩" },
      { word: "triangle", emoji: "🔺" },
      { word: "star", emoji: "⭐" },
      { word: "heart", emoji: "❤️" },
      { word: "diamond", emoji: "💎" },
      { word: "red circle", emoji: "🔴" },
      { word: "blue circle", emoji: "🔵" },
      { word: "yellow circle", emoji: "🟡" },
      { word: "purple circle", emoji: "🟣" },
      { word: "orange circle", emoji: "🟠" },
      { word: "brown circle", emoji: "🟤" },
      { word: "red square", emoji: "🟥" },
      { word: "blue square", emoji: "🟦" },
      { word: "purple square", emoji: "🟪" },
      { word: "orange square", emoji: "🟧" },
      { word: "yellow square", emoji: "🟨" },
      { word: "white circle", emoji: "⚪" },
      { word: "red triangle", emoji: "🔻" },
      { word: "blue diamond", emoji: "🔷" },
      { word: "orange diamond", emoji: "🔶" },
      { word: "pink heart", emoji: "💗" },
      { word: "purple heart", emoji: "💜" },
      { word: "blue heart", emoji: "💙" },
      { word: "green heart", emoji: "💚" },
    ],
  },

  // Level 3: Scholar (>5 years) - Complex symbols, global awareness
  {
    id: "flags",
    name: "Flags",
    description:
      "Travel the world through flags! Learn to recognize flags from different countries.",
    learningGoals: [
      "Identify country flags",
      "Learn about world geography",
      "Appreciate global diversity",
    ],
    icon: "🌍",
    level: 3,
    items: [
      { word: "United States", emoji: "🇺🇸" },
      { word: "Japan", emoji: "🇯🇵" },
      { word: "Brazil", emoji: "🇧🇷" },
      { word: "France", emoji: "🇫🇷" },
      { word: "United Kingdom", emoji: "🇬🇧" },
      { word: "Germany", emoji: "🇩🇪" },
      { word: "Italy", emoji: "🇮🇹" },
      { word: "Canada", emoji: "🇨🇦" },
      { word: "Australia", emoji: "🇦🇺" },
      { word: "Mexico", emoji: "🇲🇽" },
      { word: "China", emoji: "🇨🇳" },
      { word: "India", emoji: "🇮🇳" },
      { word: "South Korea", emoji: "🇰🇷" },
      { word: "Spain", emoji: "🇪🇸" },
      { word: "Russia", emoji: "🇷🇺" },
      { word: "South Africa", emoji: "🇿🇦" },
      { word: "Argentina", emoji: "🇦🇷" },
      { word: "Egypt", emoji: "🇪🇬" },
      { word: "Thailand", emoji: "🇹🇭" },
      { word: "Vietnam", emoji: "🇻🇳" },
      { word: "Indonesia", emoji: "🇮🇩" },
      { word: "Netherlands", emoji: "🇳🇱" },
      { word: "Sweden", emoji: "🇸🇪" },
      { word: "Switzerland", emoji: "🇨🇭" },
      { word: "Greece", emoji: "🇬🇷" },
    ],
  },
  {
    id: "celebrations",
    name: "Celebrations",
    description:
      "Party time! Discover symbols of holidays and celebrations throughout the year.",
    learningGoals: [
      "Recognize celebration symbols",
      "Learn holiday vocabulary",
      "Connect symbols to occasions",
    ],
    icon: "🎉",
    level: 3,
    items: [
      { word: "birthday", emoji: "🎂" },
      { word: "Christmas", emoji: "🎄" },
      { word: "ghost", emoji: "👻" },
      { word: "fireworks", emoji: "🎆" },
      { word: "party", emoji: "🎉" },
      { word: "gift", emoji: "🎁" },
      { word: "balloon", emoji: "🎈" },
      { word: "confetti", emoji: "🎊" },
      { word: "cupcake", emoji: "🧁" },
      { word: "sparkler", emoji: "🎇" },
      { word: "pumpkin", emoji: "🎃" },
      { word: "Santa", emoji: "🎅" },
      { word: "candy", emoji: "🍬" },
      { word: "ribbon", emoji: "🎀" },
      { word: "candle", emoji: "🕯️" },
      { word: "snowflake", emoji: "❄️" },
      { word: "heart", emoji: "❤️" },
      { word: "rose", emoji: "🌹" },
      { word: "egg", emoji: "🥚" },
      { word: "bunny", emoji: "🐰" },
      { word: "champagne", emoji: "🍾" },
      { word: "clinking glasses", emoji: "🥂" },
      { word: "trophy", emoji: "🏆" },
      { word: "pinata", emoji: "🪅" },
      { word: "disco ball", emoji: "🪩" },
    ],
  },
  {
    id: "sports",
    name: "Sports",
    description:
      "Game on! Learn about different sports and the equipment used to play them.",
    learningGoals: [
      "Identify sports and equipment",
      "Learn sports vocabulary",
      "Understand physical activities",
    ],
    icon: "⚽",
    level: 3,
    items: [
      { word: "soccer", emoji: "⚽" },
      { word: "basketball", emoji: "🏀" },
      { word: "tennis", emoji: "🎾" },
      { word: "golf", emoji: "⛳" },
      { word: "skiing", emoji: "⛷️" },
      { word: "baseball", emoji: "⚾" },
      { word: "football", emoji: "🏈" },
      { word: "volleyball", emoji: "🏐" },
      { word: "hockey", emoji: "🏒" },
      { word: "bowling", emoji: "🎳" },
      { word: "swimming", emoji: "🏊" },
      { word: "cycling", emoji: "🚴" },
      { word: "boxing", emoji: "🥊" },
      { word: "surfing", emoji: "🏄" },
      { word: "medal", emoji: "🏅" },
      { word: "martial arts", emoji: "🥋" },
      { word: "skateboard", emoji: "🛹" },
      { word: "snowboard", emoji: "🏂" },
      { word: "weight lifting", emoji: "🏋️" },
      { word: "wrestling", emoji: "🤼" },
      { word: "fencing", emoji: "🤺" },
      { word: "archery", emoji: "🏹" },
      { word: "diving", emoji: "🤿" },
      { word: "rugby", emoji: "🏉" },
      { word: "badminton", emoji: "🏸" },
    ],
  },
  {
    id: "professions",
    name: "Professions",
    description:
      "What do you want to be? Explore different jobs and the people who help our community.",
    learningGoals: [
      "Identify different professions",
      "Learn about community helpers",
      "Understand what adults do for work",
    ],
    icon: "👨‍⚕️",
    level: 3,
    items: [
      { word: "doctor", emoji: "👨‍⚕️" },
      { word: "cook", emoji: "👨‍🍳" },
      { word: "artist", emoji: "👨‍🎨" },
      { word: "pilot", emoji: "👨‍✈️" },
      { word: "teacher", emoji: "👨‍🏫" },
      { word: "firefighter", emoji: "👨‍🚒" },
      { word: "police", emoji: "👮" },
      { word: "farmer", emoji: "👨‍🌾" },
      { word: "scientist", emoji: "👨‍🔬" },
      { word: "astronaut", emoji: "👨‍🚀" },
      { word: "judge", emoji: "👨‍⚖️" },
      { word: "singer", emoji: "👨‍🎤" },
      { word: "mechanic", emoji: "👨‍🔧" },
      { word: "student", emoji: "👨‍🎓" },
      { word: "detective", emoji: "🕵️" },
      { word: "construction", emoji: "👷" },
      { word: "guard", emoji: "💂" },
      { word: "office worker", emoji: "👨‍💼" },
      { word: "factory worker", emoji: "👨‍🏭" },
      { word: "technologist", emoji: "👨‍💻" },
    ],
  },
];
