import type { Topic } from "./schema";

export const TOPICS: Topic[] = [
  // Level 1: Explorer (1-2 years) - Concrete, everyday objects
  {
    id: "animal-friends",
    name: "Animal Friends",
    descriptionMarkdown:
      "Meet friendly farm animals and pets! Perfect for little ones learning their first animal names.",
    learningGoals: [
      "Recognize common farm animals",
      "Associate animal names with their appearance",
      "Build early vocabulary",
    ],
    icon: "🐶",
    level: 1,
    items: [
      { word: "dog", emoji: "🐕" },
      { word: "cat", emoji: "🐈" },
      { word: "pig", emoji: "🐷" },
      { word: "cow", emoji: "🐄" },
      { word: "chicken", emoji: "🐔" },
      { word: "duck", emoji: "🦆" },
      { word: "horse", emoji: "🐎" },
      { word: "sheep", emoji: "🐑" },
      { word: "rabbit", emoji: "🐇" },
      { word: "fish", emoji: "🐟" },
      { word: "bird", emoji: "🐦" },
      { word: "mouse", emoji: "🐭" },
      { word: "frog", emoji: "🐸" },
      { word: "turtle", emoji: "🐢" },
      { word: "goat", emoji: "🐐" },
      { word: "hamster", emoji: "🐹" },
      { word: "chick", emoji: "🐤" },
      { word: "rooster", emoji: "🐓" },
      { word: "turkey", emoji: "🦃" },
      { word: "snail", emoji: "🐌" },
      { word: "bee", emoji: "🐝" },
      { word: "ladybug", emoji: "🐞" },
      { word: "ant", emoji: "🐜" },
      { word: "parrot", emoji: "🦜" },
      { word: "peacock", emoji: "🦚" },
    ],
  },
  {
    id: "fruits",
    name: "Fruits",
    descriptionMarkdown:
      "Discover colorful fruits from the kitchen! Learn to identify delicious fruits by their shapes and colors.",
    learningGoals: [
      "Identify common fruits",
      "Learn fruit names",
      "Connect fruits to everyday eating",
    ],
    icon: "🍎",
    level: 1,
    items: [
      { word: "apple", emoji: "🍎" },
      { word: "banana", emoji: "🍌" },
      { word: "strawberry", emoji: "🍓" },
      { word: "orange", emoji: "🍊" },
      { word: "grapes", emoji: "🍇" },
      { word: "watermelon", emoji: "🍉" },
      { word: "lemon", emoji: "🍋" },
      { word: "pear", emoji: "🍐" },
      { word: "peach", emoji: "🍑" },
      { word: "cherries", emoji: "🍒" },
      { word: "pineapple", emoji: "🍍" },
      { word: "coconut", emoji: "🥥" },
      { word: "kiwi", emoji: "🥝" },
      { word: "mango", emoji: "🥭" },
      { word: "blueberries", emoji: "🫐" },
      { word: "melon", emoji: "🍈" },
      { word: "green apple", emoji: "🍏" },
    ],
  },
  {
    id: "vehicles",
    name: "Vehicles",
    descriptionMarkdown:
      "Things that go! Explore cars, trucks, and more vehicles your child sees every day.",
    learningGoals: [
      "Name common vehicles",
      "Understand that vehicles help us travel",
      "Recognize vehicles in daily life",
    ],
    icon: "🚗",
    level: 1,
    items: [
      { word: "car", emoji: "🚗" },
      { word: "bus", emoji: "🚌" },
      { word: "train", emoji: "🚂" },
      { word: "truck", emoji: "🚚" },
      { word: "airplane", emoji: "✈️" },
      { word: "boat", emoji: "🚢" },
      { word: "bicycle", emoji: "🚲" },
      { word: "helicopter", emoji: "🚁" },
      { word: "motorcycle", emoji: "🏍️" },
      { word: "tractor", emoji: "🚜" },
      { word: "ambulance", emoji: "🚑" },
      { word: "fire truck", emoji: "🚒" },
      { word: "police car", emoji: "🚓" },
      { word: "taxi", emoji: "🚕" },
      { word: "rocket", emoji: "🚀" },
      { word: "sailboat", emoji: "⛵" },
      { word: "canoe", emoji: "🛶" },
      { word: "scooter", emoji: "🛵" },
      { word: "metro", emoji: "🚇" },
      { word: "trolley", emoji: "🚎" },
      { word: "race car", emoji: "🏎️" },
      { word: "pickup truck", emoji: "🛻" },
      { word: "minibus", emoji: "🚐" },
    ],
  },
  {
    id: "clothing",
    name: "Clothing",
    descriptionMarkdown:
      "What do we wear? Learn about everyday clothing items from head to toe.",
    learningGoals: [
      "Identify clothing items",
      "Connect clothes to body parts",
      "Build dressing vocabulary",
    ],
    icon: "👕",
    level: 1,
    items: [
      { word: "shoe", emoji: "👟" },
      { word: "shirt", emoji: "👕" },
      { word: "hat", emoji: "🎩" },
      { word: "pants", emoji: "👖" },
      { word: "dress", emoji: "👗" },
      { word: "socks", emoji: "🧦" },
      { word: "coat", emoji: "🧥" },
      { word: "gloves", emoji: "🧤" },
      { word: "scarf", emoji: "🧣" },
      { word: "boots", emoji: "🥾" },
      { word: "glasses", emoji: "👓" },
      { word: "tie", emoji: "👔" },
      { word: "crown", emoji: "👑" },
      { word: "purse", emoji: "👛" },
      { word: "backpack", emoji: "🎒" },
      { word: "sunglasses", emoji: "🕶️" },
      { word: "sandal", emoji: "🩴" },
      { word: "shorts", emoji: "🩳" },
      { word: "cap", emoji: "🧢" },
      { word: "high heel", emoji: "👠" },
      { word: "handbag", emoji: "👜" },
      { word: "watch", emoji: "⌚" },
      { word: "ring", emoji: "💍" },
    ],
  },
  {
    id: "colors",
    name: "Colors",
    descriptionMarkdown:
      "A rainbow of colors! Practice naming basic colors that are everywhere around us.",
    learningGoals: [
      "Recognize primary colors",
      "Name colors accurately",
      "Notice colors in the environment",
    ],
    icon: "🌈",
    level: 1,
    // 12 items minimum needed (session length 10 + 2 for distractor exclusion).
    // Core 10 are the standard toddler colors. Gray and gold are added to meet
    // the minimum — gray is common (elephants, clouds) and gold is familiar from
    // stickers and picture books, while being visually distinct from yellow.
    items: [
      { color: "red" },
      { color: "blue" },
      { color: "green" },
      { color: "yellow" },
      { color: "orange" },
      { color: "purple" },
      { color: "pink" },
      { color: "brown" },
      { color: "black" },
      { color: "white" },
      { color: "gray" },
      { color: "gold" },
    ],
  },
  {
    id: "flags-easy",
    name: "Famous Flags",
    descriptionMarkdown:
      "Discover the most famous flags in the world! Start your global adventure with flags everyone knows. Part of the [Flag Challenge](/topics/flags) series.",
    learningGoals: [
      "Recognize the most iconic country flags",
      "Learn names of famous countries",
      "Begin exploring the world map",
    ],
    icon: "🌍",
    level: 1,
    items: [
      { word: "United States", emoji: "🇺🇸" },
      { word: "Japan", emoji: "🇯🇵" },
      { word: "Brazil", emoji: "🇧🇷" },
      { word: "France", emoji: "🇫🇷" },
      { word: "United Kingdom", emoji: "🇬🇧" },
      { word: "Canada", emoji: "🇨🇦" },
      { word: "Germany", emoji: "🇩🇪" },
      { word: "Italy", emoji: "🇮🇹" },
      { word: "China", emoji: "🇨🇳" },
      { word: "Australia", emoji: "🇦🇺" },
      { word: "Mexico", emoji: "🇲🇽" },
      { word: "India", emoji: "🇮🇳" },
      { word: "South Korea", emoji: "🇰🇷" },
      { word: "Spain", emoji: "🇪🇸" },
      { word: "Russia", emoji: "🇷🇺" },
      { word: "Turkey", emoji: "🇹🇷" },
      { word: "South Africa", emoji: "🇿🇦" },
      { word: "Argentina", emoji: "🇦🇷" },
      { word: "Sweden", emoji: "🇸🇪" },
      { word: "Switzerland", emoji: "🇨🇭" },
      { word: "Greece", emoji: "🇬🇷" },
      { word: "Ireland", emoji: "🇮🇪" },
      { word: "New Zealand", emoji: "🇳🇿" },
      { word: "Denmark", emoji: "🇩🇰" },
      { word: "Norway", emoji: "🇳🇴" },
      { word: "Netherlands", emoji: "🇳🇱" },
      { word: "Egypt", emoji: "🇪🇬" },
      { word: "Portugal", emoji: "🇵🇹" },
      { word: "Finland", emoji: "🇫🇮" },
      { word: "Austria", emoji: "🇦🇹" },
    ],
  },

  // Level 2: Discoverer (3-5 years) - Categorization, emotions, attributes
  {
    id: "wild-animals",
    name: "Wild Animals",
    descriptionMarkdown:
      "Safari time! Discover amazing animals from jungles, oceans, and beyond.",
    learningGoals: [
      "Learn about animals from different habitats",
      "Understand animal diversity",
      "Expand animal vocabulary",
    ],
    icon: "🦁",
    level: 2,
    items: [
      { word: "lion", emoji: "🦁" },
      { word: "elephant", emoji: "🐘" },
      { word: "giraffe", emoji: "🦒" },
      { word: "zebra", emoji: "🦓" },
      { word: "monkey", emoji: "🐵" },
      { word: "bear", emoji: "🐻" },
      { word: "shark", emoji: "🦈" },
      { word: "dolphin", emoji: "🐬" },
      { word: "butterfly", emoji: "🦋" },
      { word: "octopus", emoji: "🐙" },
      { word: "penguin", emoji: "🐧" },
      { word: "kangaroo", emoji: "🦘" },
      { word: "whale", emoji: "🐋" },
      { word: "tiger", emoji: "🐅" },
      { word: "crocodile", emoji: "🐊" },
      { word: "snake", emoji: "🐍" },
      { word: "owl", emoji: "🦉" },
      { word: "fox", emoji: "🦊" },
      { word: "panda", emoji: "🐼" },
      { word: "koala", emoji: "🐨" },
      { word: "gorilla", emoji: "🦍" },
      { word: "hippo", emoji: "🦛" },
      { word: "rhino", emoji: "🦏" },
      { word: "camel", emoji: "🐪" },
      { word: "bat", emoji: "🦇" },
      { word: "eagle", emoji: "🦅" },
      { word: "flamingo", emoji: "🦩" },
      { word: "lobster", emoji: "🦞" },
      { word: "crab", emoji: "🦀" },
      { word: "jellyfish", emoji: "🪼" },
    ],
  },
  {
    id: "food",
    name: "Food",
    descriptionMarkdown:
      "Yummy foods from around the world! From pizza to noodles, discover tasty treats.",
    learningGoals: [
      "Identify various foods",
      "Learn food vocabulary",
      "Connect food to meals",
    ],
    icon: "🍕",
    level: 2,
    items: [
      { word: "pizza", emoji: "🍕" },
      { word: "ice cream", emoji: "🍦" },
      { word: "hamburger", emoji: "🍔" },
      { word: "donut", emoji: "🍩" },
      { word: "popcorn", emoji: "🍿" },
      { word: "cake", emoji: "🎂" },
      { word: "cookie", emoji: "🍪" },
      { word: "bread", emoji: "🍞" },
      { word: "cheese", emoji: "🧀" },
      { word: "egg", emoji: "🥚" },
      { word: "rice", emoji: "🍚" },
      { word: "noodles", emoji: "🍜" },
      { word: "hot dog", emoji: "🌭" },
      { word: "taco", emoji: "🌮" },
      { word: "sushi", emoji: "🍣" },
      { word: "bacon", emoji: "🥓" },
      { word: "salad", emoji: "🥗" },
      { word: "french fries", emoji: "🍟" },
      { word: "sandwich", emoji: "🥪" },
      { word: "pancakes", emoji: "🥞" },
      { word: "waffle", emoji: "🧇" },
      { word: "pretzel", emoji: "🥨" },
      { word: "croissant", emoji: "🥐" },
      { word: "burrito", emoji: "🌯" },
      { word: "steak", emoji: "🥩" },
      { word: "shrimp", emoji: "🍤" },
      { word: "dumpling", emoji: "🥟" },
      { word: "pie", emoji: "🥧" },
      { word: "chocolate", emoji: "🍫" },
      { word: "lollipop", emoji: "🍭" },
    ],
  },
  {
    id: "nature",
    name: "Nature",
    descriptionMarkdown:
      "Explore the natural world! From sunny skies to snowy mountains, discover nature's wonders.",
    learningGoals: [
      "Identify natural phenomena",
      "Learn about weather and landscapes",
      "Appreciate the natural world",
    ],
    icon: "🌻",
    level: 2,
    items: [
      { word: "sun", emoji: "☀️" },
      { word: "rain", emoji: "🌧️" },
      { word: "rainbow", emoji: "🌈" },
      { word: "cloud", emoji: "☁️" },
      { word: "snow", emoji: "❄️" },
      { word: "star", emoji: "⭐" },
      { word: "moon", emoji: "🌙" },
      { word: "rose", emoji: "🌹" },
      { word: "sunflower", emoji: "🌻" },
      { word: "tree", emoji: "🌳" },
      { word: "mushroom", emoji: "🍄" },
      { word: "mountain", emoji: "⛰️" },
      { word: "volcano", emoji: "🌋" },
      { word: "beach", emoji: "🏖️" },
      { word: "wave", emoji: "🌊" },
      { word: "fire", emoji: "🔥" },
      { word: "snowman", emoji: "⛄" },
      { word: "cactus", emoji: "🌵" },
      { word: "tulip", emoji: "🌷" },
      { word: "leaf", emoji: "🍃" },
      { word: "palm tree", emoji: "🌴" },
      { word: "lightning", emoji: "⚡" },
      { word: "tornado", emoji: "🌪️" },
      { word: "comet", emoji: "☄️" },
      { word: "full moon", emoji: "🌕" },
      { word: "hibiscus", emoji: "🌺" },
      { word: "desert island", emoji: "🏝️" },
      { word: "sunrise", emoji: "🌅" },
      { word: "clover", emoji: "🍀" },
      { word: "shell", emoji: "🐚" },
    ],
  },
  {
    id: "emotions",
    name: "Emotions",
    descriptionMarkdown:
      "How do you feel? Learn to recognize and name different emotions and feelings.",
    learningGoals: [
      "Identify facial expressions",
      "Name common emotions",
      "Build emotional vocabulary",
    ],
    icon: "😊",
    level: 2,
    items: [
      { word: "happy", emoji: "😊" },
      { word: "sad", emoji: "😢" },
      { word: "angry", emoji: "😠" },
      { word: "scared", emoji: "😨" },
      { word: "sleepy", emoji: "😴" },
      { word: "love", emoji: "🥰" },
      { word: "worried", emoji: "😟" },
      { word: "crying", emoji: "😭" },
      { word: "thinking", emoji: "🤔" },
      { word: "confused", emoji: "😕" },
      { word: "surprised", emoji: "😮" },
      { word: "silly", emoji: "🤪" },
      { word: "cool", emoji: "😎" },
      { word: "sick", emoji: "🤒" },
      { word: "laughing", emoji: "😂" },
      { word: "winking", emoji: "😉" },
      { word: "shy", emoji: "😳" },
      { word: "hungry", emoji: "🤤" },
      { word: "yawning", emoji: "🥱" },
      { word: "excited", emoji: "🤩" },
    ],
  },
  {
    id: "shapes",
    name: "Shapes",
    descriptionMarkdown:
      "Shapes are everywhere! Learn to spot circles, squares, and more geometric friends.",
    learningGoals: [
      "Recognize basic shapes",
      "Find shapes in everyday objects",
      "Build spatial awareness",
    ],
    icon: "⭐",
    level: 2,
    items: [
      { word: "circle", emoji: "⚫" },
      { word: "square", emoji: "🟩" },
      { word: "triangle", emoji: "🔺" },
      { word: "star", emoji: "⭐" },
      { word: "heart", emoji: "❤️" },
      { word: "diamond", emoji: "💎" },
      { word: "red circle", emoji: "🔴" },
      { word: "blue circle", emoji: "🔵" },
      { word: "yellow circle", emoji: "🟡" },
      { word: "purple circle", emoji: "🟣" },
      { word: "orange circle", emoji: "🟠" },
      { word: "brown circle", emoji: "🟤" },
      { word: "red square", emoji: "🟥" },
      { word: "blue square", emoji: "🟦" },
      { word: "purple square", emoji: "🟪" },
      { word: "orange square", emoji: "🟧" },
      { word: "yellow square", emoji: "🟨" },
      { word: "white circle", emoji: "⚪" },
      { word: "red triangle", emoji: "🔻" },
      { word: "blue diamond", emoji: "🔷" },
      { word: "orange diamond", emoji: "🔶" },
      { word: "pink heart", emoji: "💗" },
      { word: "purple heart", emoji: "💜" },
      { word: "blue heart", emoji: "💙" },
      { word: "green heart", emoji: "💚" },
    ],
  },
  {
    id: "telling-time",
    name: "Telling Time",
    descriptionMarkdown:
      "What time is it? Learn to read clock faces by matching times to analog clocks!",
    learningGoals: [
      "Read hour and half-hour positions on a clock",
      "Associate time words with clock faces",
      "Build early time-telling skills",
    ],
    icon: "🕐",
    level: 2,
    items: [
      { word: "one o'clock", emoji: "🕐" },
      { word: "two o'clock", emoji: "🕑" },
      { word: "three o'clock", emoji: "🕒" },
      { word: "four o'clock", emoji: "🕓" },
      { word: "five o'clock", emoji: "🕔" },
      { word: "six o'clock", emoji: "🕕" },
      { word: "seven o'clock", emoji: "🕖" },
      { word: "eight o'clock", emoji: "🕗" },
      { word: "nine o'clock", emoji: "🕘" },
      { word: "ten o'clock", emoji: "🕙" },
      { word: "eleven o'clock", emoji: "🕚" },
      { word: "twelve o'clock", emoji: "🕛" },
      { word: "one thirty", emoji: "🕜" },
      { word: "two thirty", emoji: "🕝" },
      { word: "three thirty", emoji: "🕞" },
      { word: "four thirty", emoji: "🕟" },
      { word: "five thirty", emoji: "🕠" },
      { word: "six thirty", emoji: "🕡" },
      { word: "seven thirty", emoji: "🕢" },
      { word: "eight thirty", emoji: "🕣" },
      { word: "nine thirty", emoji: "🕤" },
      { word: "ten thirty", emoji: "🕥" },
      { word: "eleven thirty", emoji: "🕦" },
      { word: "twelve thirty", emoji: "🕧" },
    ],
  },
  {
    id: "12-con-giap",
    name: "12 Con Giáp",
    descriptionMarkdown:
      "Learn the 12 animals of the Vietnamese zodiac! Match each animal to its traditional name.",
    learningGoals: [
      "Recognize the 12 Vietnamese zodiac animals",
      "Learn traditional zodiac branch names",
      "Explore Vietnamese cultural traditions",
    ],
    icon: "🐉",
    level: 2,
    speechLang: "vi-VN",
    items: [
      { word: "Tí", emoji: "🐀" },
      { word: "Sửu", emoji: "🐃" },
      { word: "Dần", emoji: "🐅" },
      { word: "Mão", emoji: "🐈" },
      { word: "Thìn", emoji: "🐉" },
      { word: "Tỵ", emoji: "🐍" },
      { word: "Ngọ", emoji: "🐎" },
      { word: "Mùi", emoji: "🐐" },
      { word: "Thân", emoji: "🐒" },
      { word: "Dậu", emoji: "🐓" },
      { word: "Tuất", emoji: "🐕" },
      { word: "Hợi", emoji: "🐖" },
    ],
  },
  {
    id: "flags-medium",
    name: "World Flags",
    descriptionMarkdown:
      "Explore more flags from around the globe! Challenge yourself with flags from every continent. Part of the [Flag Challenge](/topics/flags) series.",
    learningGoals: [
      "Identify flags from diverse regions",
      "Learn about countries across all continents",
      "Understand geographic diversity through flags",
    ],
    icon: "🗺️",
    level: 2,
    items: [
      { word: "Thailand", emoji: "🇹🇭" },
      { word: "Vietnam", emoji: "🇻🇳" },
      { word: "Indonesia", emoji: "🇮🇩" },
      { word: "Poland", emoji: "🇵🇱" },
      { word: "Belgium", emoji: "🇧🇪" },
      { word: "Philippines", emoji: "🇵🇭" },
      { word: "Colombia", emoji: "🇨🇴" },
      { word: "Chile", emoji: "🇨🇱" },
      { word: "Peru", emoji: "🇵🇪" },
      { word: "Nigeria", emoji: "🇳🇬" },
      { word: "Kenya", emoji: "🇰🇪" },
      { word: "Israel", emoji: "🇮🇱" },
      { word: "Saudi Arabia", emoji: "🇸🇦" },
      { word: "Ukraine", emoji: "🇺🇦" },
      { word: "Singapore", emoji: "🇸🇬" },
      { word: "Malaysia", emoji: "🇲🇾" },
      { word: "Pakistan", emoji: "🇵🇰" },
      { word: "Cuba", emoji: "🇨🇺" },
      { word: "Morocco", emoji: "🇲🇦" },
      { word: "Jamaica", emoji: "🇯🇲" },
      { word: "Czech Republic", emoji: "🇨🇿" },
      { word: "Romania", emoji: "🇷🇴" },
      { word: "Hungary", emoji: "🇭🇺" },
      { word: "Croatia", emoji: "🇭🇷" },
      { word: "Serbia", emoji: "🇷🇸" },
      { word: "Iceland", emoji: "🇮🇸" },
      { word: "Taiwan", emoji: "🇹🇼" },
      { word: "Iran", emoji: "🇮🇷" },
      { word: "Iraq", emoji: "🇮🇶" },
      { word: "Bangladesh", emoji: "🇧🇩" },
      { word: "Ethiopia", emoji: "🇪🇹" },
      { word: "Ghana", emoji: "🇬🇭" },
      { word: "Tanzania", emoji: "🇹🇿" },
      { word: "Costa Rica", emoji: "🇨🇷" },
      { word: "Dominican Republic", emoji: "🇩🇴" },
    ],
  },

  // Level 3: Scholar (>5 years) - Complex symbols, global awareness
  {
    id: "flags-hard",
    name: "Flag Expert Challenge",
    descriptionMarkdown:
      "The ultimate flag challenge! Can you identify these tricky flags from lesser-known countries and territories? Part of the [Flag Challenge](/topics/flags) series.",
    learningGoals: [
      "Identify flags from lesser-known countries",
      "Distinguish similar-looking flags",
      "Develop expert-level geography knowledge",
    ],
    icon: "🏴",
    level: 3,
    items: [
      { word: "Nepal", emoji: "🇳🇵" },
      { word: "Bhutan", emoji: "🇧🇹" },
      { word: "Sri Lanka", emoji: "🇱🇰" },
      { word: "Cambodia", emoji: "🇰🇭" },
      { word: "Myanmar", emoji: "🇲🇲" },
      { word: "Mongolia", emoji: "🇲🇳" },
      { word: "Qatar", emoji: "🇶🇦" },
      { word: "Bahrain", emoji: "🇧🇭" },
      { word: "Mozambique", emoji: "🇲🇿" },
      { word: "Eswatini", emoji: "🇸🇿" },
      { word: "Brunei", emoji: "🇧🇳" },
      { word: "Laos", emoji: "🇱🇦" },
      { word: "Honduras", emoji: "🇭🇳" },
      { word: "Guatemala", emoji: "🇬🇹" },
      { word: "El Salvador", emoji: "🇸🇻" },
      { word: "Panama", emoji: "🇵🇦" },
      { word: "Uzbekistan", emoji: "🇺🇿" },
      { word: "Kazakhstan", emoji: "🇰🇿" },
      { word: "Azerbaijan", emoji: "🇦🇿" },
      { word: "Georgia", emoji: "🇬🇪" },
      { word: "North Macedonia", emoji: "🇲🇰" },
      { word: "Montenegro", emoji: "🇲🇪" },
      { word: "Moldova", emoji: "🇲🇩" },
      { word: "Liechtenstein", emoji: "🇱🇮" },
      { word: "Andorra", emoji: "🇦🇩" },
      { word: "Suriname", emoji: "🇸🇷" },
      { word: "Maldives", emoji: "🇲🇻" },
      { word: "Fiji", emoji: "🇫🇯" },
      { word: "Tonga", emoji: "🇹🇴" },
      { word: "Barbados", emoji: "🇧🇧" },
      { word: "Djibouti", emoji: "🇩🇯" },
      { word: "Eritrea", emoji: "🇪🇷" },
      { word: "Kyrgyzstan", emoji: "🇰🇬" },
      { word: "Turkmenistan", emoji: "🇹🇲" },
      { word: "Armenia", emoji: "🇦🇲" },
      { word: "Bolivia", emoji: "🇧🇴" },
      { word: "Paraguay", emoji: "🇵🇾" },
      { word: "Uruguay", emoji: "🇺🇾" },
      { word: "Madagascar", emoji: "🇲🇬" },
      { word: "Senegal", emoji: "🇸🇳" },
      { word: "Tunisia", emoji: "🇹🇳" },
      { word: "Algeria", emoji: "🇩🇿" },
      { word: "Jordan", emoji: "🇯🇴" },
      { word: "Lebanon", emoji: "🇱🇧" },
      { word: "Oman", emoji: "🇴🇲" },
      { word: "Papua New Guinea", emoji: "🇵🇬" },
      { word: "Belize", emoji: "🇧🇿" },
      { word: "Trinidad and Tobago", emoji: "🇹🇹" },
      { word: "Latvia", emoji: "🇱🇻" },
      { word: "Lithuania", emoji: "🇱🇹" },
    ],
  },
  {
    id: "world-cup-stars",
    name: "World Cup Stars",
    descriptionMarkdown:
      "Meet football stars from around the world! Match each famous player with the country they represent.",
    learningGoals: [
      "Recognize famous international football players",
      "Match players with their national teams",
      "Explore countries through football",
    ],
    icon: "🏆",
    level: 3,
    items: [
      { word: "Lionel Messi", emoji: "🇦🇷" },
      { word: "Cristiano Ronaldo", emoji: "🇵🇹" },
      { word: "Kylian Mbappé", emoji: "🇫🇷" },
      { word: "Neymar", emoji: "🇧🇷" },
      { word: "Luka Modrić", emoji: "🇭🇷" },
      { word: "Lamine Yamal", emoji: "🇪🇸" },
      { word: "Manuel Neuer", emoji: "🇩🇪" },
      { word: "Virgil van Dijk", emoji: "🇳🇱" },
      { word: "Kevin De Bruyne", emoji: "🇧🇪" },
      { word: "Erling Haaland", emoji: "🇳🇴" },
      { word: "Christian Pulisic", emoji: "🇺🇸" },
      { word: "Alphonso Davies", emoji: "🇨🇦" },
      { word: "Achraf Hakimi", emoji: "🇲🇦" },
      { word: "Mohamed Salah", emoji: "🇪🇬" },
      { word: "Sadio Mané", emoji: "🇸🇳" },
      { word: "Riyad Mahrez", emoji: "🇩🇿" },
      { word: "Viktor Gyökeres", emoji: "🇸🇪" },
      { word: "Granit Xhaka", emoji: "🇨🇭" },
      { word: "Federico Valverde", emoji: "🇺🇾" },
      { word: "Luis Díaz", emoji: "🇨🇴" },
      { word: "Moisés Caicedo", emoji: "🇪🇨" },
      { word: "Son Heung-min", emoji: "🇰🇷" },
      { word: "Akram Afif", emoji: "🇶🇦" },
      { word: "Salem Al-Dawsari", emoji: "🇸🇦" },
    ],
  },
  {
    id: "celebrations",
    name: "Celebrations",
    descriptionMarkdown:
      "Party time! Discover symbols of holidays and celebrations throughout the year.",
    learningGoals: [
      "Recognize celebration symbols",
      "Learn holiday vocabulary",
      "Connect symbols to occasions",
    ],
    icon: "🎉",
    level: 3,
    items: [
      { word: "birthday", emoji: "🎂" },
      { word: "Christmas", emoji: "🎄" },
      { word: "ghost", emoji: "👻" },
      { word: "fireworks", emoji: "🎆" },
      { word: "party", emoji: "🎉" },
      { word: "gift", emoji: "🎁" },
      { word: "balloon", emoji: "🎈" },
      { word: "confetti", emoji: "🎊" },
      { word: "cupcake", emoji: "🧁" },
      { word: "sparkler", emoji: "🎇" },
      { word: "pumpkin", emoji: "🎃" },
      { word: "Santa", emoji: "🎅" },
      { word: "candy", emoji: "🍬" },
      { word: "ribbon", emoji: "🎀" },
      { word: "candle", emoji: "🕯️" },
      { word: "snowflake", emoji: "❄️" },
      { word: "heart", emoji: "❤️" },
      { word: "rose", emoji: "🌹" },
      { word: "egg", emoji: "🥚" },
      { word: "bunny", emoji: "🐰" },
      { word: "champagne", emoji: "🍾" },
      { word: "clinking glasses", emoji: "🥂" },
      { word: "trophy", emoji: "🏆" },
      { word: "pinata", emoji: "🪅" },
      { word: "disco ball", emoji: "🪩" },
    ],
  },
  {
    id: "sports",
    name: "Sports",
    descriptionMarkdown:
      "Game on! Learn about different sports and the equipment used to play them.",
    learningGoals: [
      "Identify sports and equipment",
      "Learn sports vocabulary",
      "Understand physical activities",
    ],
    icon: "⚽",
    level: 3,
    items: [
      { word: "soccer", emoji: "⚽" },
      { word: "basketball", emoji: "🏀" },
      { word: "tennis", emoji: "🎾" },
      { word: "golf", emoji: "⛳" },
      { word: "skiing", emoji: "⛷️" },
      { word: "baseball", emoji: "⚾" },
      { word: "football", emoji: "🏈" },
      { word: "volleyball", emoji: "🏐" },
      { word: "hockey", emoji: "🏒" },
      { word: "bowling", emoji: "🎳" },
      { word: "swimming", emoji: "🏊" },
      { word: "cycling", emoji: "🚴" },
      { word: "boxing", emoji: "🥊" },
      { word: "surfing", emoji: "🏄" },
      { word: "medal", emoji: "🏅" },
      { word: "martial arts", emoji: "🥋" },
      { word: "skateboard", emoji: "🛹" },
      { word: "snowboard", emoji: "🏂" },
      { word: "weight lifting", emoji: "🏋️" },
      { word: "wrestling", emoji: "🤼" },
      { word: "fencing", emoji: "🤺" },
      { word: "archery", emoji: "🏹" },
      { word: "diving", emoji: "🤿" },
      { word: "rugby", emoji: "🏉" },
      { word: "badminton", emoji: "🏸" },
    ],
  },
  {
    id: "professions",
    name: "Professions",
    descriptionMarkdown:
      "What do you want to be? Explore different jobs and the people who help our community.",
    learningGoals: [
      "Identify different professions",
      "Learn about community helpers",
      "Understand what adults do for work",
    ],
    icon: "👨‍⚕️",
    level: 3,
    items: [
      { word: "doctor", emoji: "👨‍⚕️" },
      { word: "cook", emoji: "👨‍🍳" },
      { word: "artist", emoji: "👨‍🎨" },
      { word: "pilot", emoji: "👨‍✈️" },
      { word: "teacher", emoji: "👨‍🏫" },
      { word: "firefighter", emoji: "👨‍🚒" },
      { word: "police", emoji: "👮" },
      { word: "farmer", emoji: "👨‍🌾" },
      { word: "scientist", emoji: "👨‍🔬" },
      { word: "astronaut", emoji: "👨‍🚀" },
      { word: "judge", emoji: "👨‍⚖️" },
      { word: "singer", emoji: "👨‍🎤" },
      { word: "mechanic", emoji: "👨‍🔧" },
      { word: "student", emoji: "👨‍🎓" },
      { word: "detective", emoji: "🕵️" },
      { word: "construction", emoji: "👷" },
      { word: "guard", emoji: "💂" },
      { word: "office worker", emoji: "👨‍💼" },
      { word: "factory worker", emoji: "👨‍🏭" },
      { word: "technologist", emoji: "👨‍💻" },
    ],
  },
];
