/**
 * Words from google-10000-english.txt that SHOULD have emoji mappings
 * but currently don't. These represent opportunities for improvement.
 *
 * Format: [word, expectedEmoji, reason/notes]
 */

export const EXPECTED_EMOJI_MAPPINGS: Array<[string, string, string]> = [
  // People & Family
  ["people", "👥", "generic people group"],
  ["family", "👪", "family group"],
  ["friend", "👫", "friends/people together"],
  ["friends", "👯", "dancing people/friends"],
  ["children", "🧒", "child (already mapped but should be validated)"],
  ["teen", "🧑", "teenager/young person"],
  ["young", "🧒", "young person"],
  ["john", "🧔", "common male name → bearded person"],
  ["member", "👤", "person silhouette"],
  ["members", "👥", "people silhouettes"],
  ["author", "✍️", "writing/author"],
  ["user", "👤", "user profile icon"],
  ["users", "👥", "multiple users"],
  ["customer", "🛒", "customer/shopping"],

  // Animals & Nature
  ["animal", "🐾", "animal tracks"],
  ["animals", "🐾", "animal tracks"],
  ["pet", "🐕", "pet/dog"],
  ["pets", "🐾", "pets/animal tracks"],
  ["nature", "🌿", "nature/herb"],
  ["forest", "🌲", "forest/evergreen"],
  ["ocean", "🌊", "ocean wave"],
  ["lake", "🏞️", "lake in national park"],
  ["river", "🌊", "river/water"],
  ["sea", "🌊", "sea/ocean"],

  // Weather & Time
  ["weather", "🌤️", "sun behind cloud"],
  ["storm", "⛈️", "thunderstorm"],
  ["cloud", "☁️", "cloud"],
  ["clouds", "☁️", "clouds"],
  ["sunny", "☀️", "sun"],
  ["morning", "🌅", "sunrise"],
  ["afternoon", "🌆", "cityscape at dusk"],
  ["week", "📅", "calendar"],
  ["month", "📆", "calendar"],
  ["year", "📅", "calendar"],
  ["today", "📅", "today/calendar"],
  ["date", "📅", "date/calendar"],
  ["hours", "⏰", "clock/hours"],
  ["hour", "⏰", "clock"],
  ["minute", "⏱️", "stopwatch/timer"],
  ["minutes", "⏱️", "stopwatch"],
  ["second", "🥈", "already mapped but validate"],

  // Places & Geography
  ["place", "📍", "already mapped but validate"],
  ["location", "📍", "already mapped but validate"],
  ["area", "🗺️", "map/area"],
  ["map", "🗺️", "world map"],
  ["world", "🌍", "globe"],
  ["earth", "🌍", "globe"],
  ["street", "🛣️", "road/street"],
  ["street", "🏘️", "houses/neighborhood"],
  ["north", "⬆️", "north direction"],
  ["south", "⬇️", "south direction"],
  ["states", "🇺🇸", "United States"],
  ["usa", "🇺🇸", "United States"],
  ["america", "🇺🇸", "America/US flag"],
  ["uk", "🇬🇧", "United Kingdom"],
  ["county", "🏛️", "government building"],
  ["state", "🏛️", "state/government"],
  ["government", "🏛️", "government building"],
  ["international", "🌐", "globe with meridians"],
  ["country", "🌐", "country/globe"],
  ["san", "🌁", "San Francisco fog"],
  ["la", "🌴", "Los Angeles palm tree"],

  // Buildings & Structures
  ["hotel", "🏨", "already mapped but validate"],
  ["hotels", "🏨", "hotels"],
  ["room", "🚪", "room/door"],
  ["center", "🏢", "center/office building"],
  ["estate", "🏡", "real estate/house"],
  ["property", "🏠", "property/house"],
  ["stores", "🏬", "stores/department store"],
  ["shop", "🛍️", "shopping bags"],
  ["travel", "✈️", "travel/airplane"],

  // Technology & Computers
  ["technology", "💻", "technology/laptop"],
  ["digital", "💾", "digital/floppy disk"],
  ["internet", "🌐", "internet/globe"],
  ["site", "🌐", "website/globe"],
  ["sites", "🌐", "websites"],
  ["software", "💿", "software/optical disc"],
  ["computer", "💻", "already mapped but validate"],
  ["windows", "🪟", "windows"],
  ["server", "🖥️", "server/desktop computer"],
  ["memory", "💾", "memory/storage"],
  ["code", "💻", "code/programming"],
  ["program", "💻", "computer program"],
  ["programs", "💻", "programs"],
  ["system", "💻", "computer system"],
  ["systems", "💻", "systems"],
  ["download", "⬇️", "download arrow"],
  ["version", "🔢", "version number"],

  // Communication
  ["contact", "📞", "contact/telephone"],
  ["phone", "📱", "already mapped but validate"],
  ["email", "📧", "already mapped but validate"],
  ["message", "💬", "already mapped but validate"],
  ["comment", "💬", "comment/speech balloon"],
  ["comments", "💬", "comments"],
  ["reply", "↩️", "reply arrow"],
  ["feedback", "💬", "feedback"],
  ["quote", "💬", "quotation"],
  ["topic", "💭", "topic/thought balloon"],
  ["chat", "💬", "chat"],
  ["forum", "💬", "forum/discussion"],
  ["forums", "💬", "forums"],

  // Education & Knowledge
  ["education", "🎓", "education/graduation"],
  ["school", "🏫", "already mapped but validate"],
  ["university", "🏫", "university/school"],
  ["college", "🏫", "college/school"],
  ["student", "🧑‍🎓", "already mapped but validate"],
  ["students", "🧑‍🎓", "students"],
  ["learn", "📚", "learn/books"],
  ["course", "📚", "course/books"],
  ["training", "📚", "training/books"],
  ["science", "🔬", "science/microscope"],
  ["research", "🔬", "research/microscope"],
  ["history", "📜", "history/scroll"],
  ["article", "📰", "article/newspaper"],
  ["articles", "📰", "articles"],
  ["blog", "📝", "blog/memo"],
  ["story", "📖", "story/book"],
  ["language", "🗣️", "language/speaking head"],

  // Business & Finance
  ["business", "💼", "business/briefcase"],
  ["company", "🏢", "company/office building"],
  ["financial", "💰", "financial/money bag"],
  ["sales", "💰", "sales/money"],
  ["price", "💲", "price/dollar sign"],
  ["prices", "💲", "prices"],
  ["cost", "💵", "cost/dollar"],
  ["payment", "💳", "payment/credit card"],
  ["tax", "💸", "tax/money with wings"],
  ["insurance", "🛡️", "insurance/shield"],
  ["stock", "📈", "stock/chart increasing"],
  ["industry", "🏭", "industry/factory"],
  ["sale", "🏷️", "sale/label"],
  ["team", "👥", "team/people"],
  ["plan", "📋", "plan/clipboard"],
  ["model", "📊", "model/chart"],
  ["standard", "✅", "standard/check mark"],
  ["quality", "⭐", "quality/star"],
  ["performance", "📊", "performance/chart"],
  ["rating", "⭐", "rating/star"],
  ["rate", "⭐", "rate/star"],

  // Shopping & Products
  ["products", "📦", "products/package"],
  ["product", "📦", "product/package"],
  ["items", "🛍️", "items/shopping bags"],
  ["item", "🛍️", "item/shopping bag"],
  ["buy", "🛒", "buy/shopping cart"],
  ["shopping", "🛍️", "already mapped but validate"],
  ["cart", "🛒", "already mapped but validate"],
  ["accessories", "👜", "accessories/handbag"],
  ["equipment", "🔧", "equipment/wrench"],
  ["tools", "🧰", "already mapped but validate"],

  // Media & Entertainment
  ["movie", "🎥", "already mapped but validate"],
  ["movies", "🎬", "movies/clapper board"],
  ["video", "📹", "video camera"],
  ["picture", "🖼️", "already mapped but validate"],
  ["pictures", "🖼️", "pictures"],
  ["photo", "📷", "already mapped but validate"],
  ["photos", "📷", "photos"],
  ["image", "🖼️", "image/framed picture"],
  ["gallery", "🖼️", "gallery/picture frame"],
  ["art", "🎨", "art/palette"],
  ["design", "🎨", "design/palette"],
  ["model", "📸", "model/camera"],
  ["series", "📺", "TV series"],

  // Documents & Forms
  ["document", "📄", "document/page"],
  ["documents", "📄", "documents"],
  ["form", "📋", "form/clipboard"],
  ["forms", "📋", "forms"],
  ["report", "📊", "report/bar chart"],
  ["page", "📃", "already mapped but validate"],
  ["pages", "📃", "pages"],
  ["title", "📰", "title/newspaper"],
  ["content", "📝", "content/memo"],
  ["section", "📑", "section/bookmark tabs"],
  ["details", "📋", "details/clipboard"],
  ["description", "📝", "description/memo"],
  ["source", "📄", "source/document"],
  ["terms", "📄", "terms/document"],
  ["conditions", "📄", "conditions/document"],
  ["legal", "⚖️", "legal/scales"],
  ["act", "⚖️", "act/law"],
  ["policy", "📄", "policy/document"],
  ["register", "📝", "register/memo"],
  ["login", "🔐", "login/locked with key"],
  ["account", "👤", "account/bust in silhouette"],
  ["profile", "👤", "profile"],

  // Numbers & Data
  ["number", "🔢", "number/input numbers"],
  ["data", "💾", "data/floppy disk"],
  ["info", "ℹ️", "already mapped but validate"],
  ["size", "📏", "size/ruler"],
  ["value", "💎", "value/gem stone"],
  ["results", "📊", "results/chart"],
  ["rating", "⭐", "rating/star"],
  ["status", "📊", "status/chart"],
  ["level", "🎚️", "already mapped but validate"],

  // Actions & Activities
  ["search", "🔍", "search/magnifying glass"],
  ["find", "🔎", "find/magnifying glass"],
  ["create", "➕", "create/plus"],
  ["select", "☑️", "select/check box"],
  ["show", "👁️", "show/eye"],
  ["help", "❓", "help/question mark"],
  ["review", "⭐", "review/star"],
  ["reviews", "⭐", "reviews"],
  ["visit", "👣", "visit/footprints"],
  ["register", "📝", "register/memo"],
  ["login", "🔑", "login/key"],
  ["join", "➕", "join/plus"],
  ["reply", "↩️", "reply/return arrow"],
  ["return", "↩️", "return arrow"],
  ["compare", "⚖️", "compare/balance scale"],
  ["activity", "⚡", "activity/high voltage"],
  ["activities", "⚡", "activities"],

  // Time periods
  ["january", "📅", "January/calendar"],
  ["february", "📅", "February/calendar"],
  ["march", "📅", "March/calendar"],
  ["april", "📅", "April/calendar"],
  ["may", "📅", "May/calendar"],
  ["june", "📅", "June/calendar"],
  ["july", "📅", "July/calendar"],
  ["august", "📅", "August/calendar"],
  ["september", "📅", "September/calendar"],
  ["october", "📅", "October/calendar"],
  ["november", "📅", "November/calendar"],
  ["december", "📅", "December/calendar"],
  ["jan", "📅", "Jan/calendar"],
  ["dec", "📅", "Dec/calendar"],

  // Food & Dining
  ["food", "🍲", "already mapped but validate"],
  ["restaurant", "🍽️", "restaurant/fork and knife with plate"],
  ["dining", "🍽️", "dining"],
  ["lunch", "🥗", "lunch/green salad"],
  ["meal", "🍽️", "meal/plate"],
  ["cooking", "🍳", "cooking/frying pan"],
  ["recipe", "📖", "recipe/book"],
  ["recipes", "📖", "recipes"],

  // Colors
  ["color", "🎨", "color/palette"],
  ["colors", "🎨", "colors"],

  // Size & Measurement
  ["small", "🔹", "small/small blue diamond"],
  ["large", "🔷", "large/large blue diamond"],
  ["big", "🔷", "big/large diamond"],
  ["little", "🔹", "little/small diamond"],

  // Quality indicators
  ["new", "🆕", "new button"],
  ["best", "🏆", "best/trophy"],
  ["special", "⭐", "special/star"],
  ["popular", "🔥", "popular/fire"],
  ["top", "🔝", "top/up arrow"],
  ["advanced", "⚡", "advanced/high voltage"],
  ["standard", "✅", "standard/check mark"],

  // Community & Social
  ["community", "👥", "community/people"],
  ["social", "👥", "social/people"],
  ["member", "👤", "member/person"],
  ["group", "👥", "group/people"],
  ["forum", "💬", "forum/chat"],
  ["posts", "📌", "posts/pushpin"],
  ["posted", "📌", "posted/pushpin"],

  // Questions & Support
  ["questions", "❓", "questions"],
  ["question", "❓", "already mapped but validate"],
  ["problem", "⚠️", "problem/warning"],
  ["issues", "⚠️", "issues/warning"],
  ["support", "🆘", "support/SOS"],

  // Generic concepts that could map
  ["resources", "📚", "resources/books"],
  ["development", "🔧", "development/tools"],
  ["features", "✨", "features/sparkles"],
  ["options", "⚙️", "options/gear"],
  ["offers", "🎁", "offers/gift"],
  ["process", "⚙️", "process/gear"],
  ["services", "🛎️", "services/bellhop bell"],
  ["service", "🛎️", "service/bellhop bell"],
  ["listing", "📋", "listing/clipboard"],
  ["directory", "📁", "directory/folder"],
  ["categories", "📑", "categories/bookmark tabs"],
  ["category", "📑", "already mapped but validate"],
  ["events", "🎉", "events/party popper"],
  ["event", "🎉", "event/party"],
];
